export const plans = [
  {
    id: "standard-ads",
    name: "Padrão com anúncios",
    resolution: "1080p",
    quality: "Boa",
    resolutionFull: "Full HD (1080p)",
    audio: "—",
    devices: "TV, computador, celular, tablet",
    streams: 2,
    downloads: 2,
    originalPrice: 18.9,
    price: 9.45,
  },
  {
    id: "standard",
    name: "Padrão",
    resolution: "1080p",
    quality: "Boa",
    resolutionFull: "Full HD (1080p)",
    audio: "—",
    devices: "TV, computador, celular, tablet",
    streams: 2,
    downloads: 2,
    originalPrice: 34.9,
    price: 17.45,
  },
  {
    id: "premium",
    name: "Premium",
    resolution: "4K + HDR",
    quality: "Superior",
    resolutionFull: "4K (Ultra HD) + HDR",
    audio: "Incluso",
    devices: "TV, computador, celular, tablet",
    streams: 4,
    downloads: 6,
    originalPrice: 59.9,
    price: 29.95,
  },
];
